- hosts: all
  become: true
  tasks:
    - name: install virtual frame buffer
      yum:
        name: xorg-x11-server-Xvfb
        state: present
    - name: install selenium
      pip:
        name: 'selenium<4'
        state: present
    - name: install firefox
      yum:
        name: firefox
        state: present
    - name: fetch firefox driver
      get_url:
        url: https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
        dest: /tmp/geckodriver.tar.gz
    - name: unpack firefox driver
      unarchive:
        src: /tmp/geckodriver.tar.gz
        dest: /usr/local/bin
        remote_src: true
    - name: check selenium version
      command: pip show selenium
    - name: check firefox version
      command: firefox --version
    #- name: install chromium
    #  yum:
    #    name: chromium-headless
    #    state: present
