// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fmgr.proto

package filemgr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Volume type
type VolumeType int32

const (
	VolumeType_VOLUME_DEFAULT     VolumeType = 0
	VolumeType_VOLUME_TOMBSTONE   VolumeType = 1
	VolumeType_VOLUME_X_DELETE_AT VolumeType = 2
)

var VolumeType_name = map[int32]string{
	0: "VOLUME_DEFAULT",
	1: "VOLUME_TOMBSTONE",
	2: "VOLUME_X_DELETE_AT",
}

var VolumeType_value = map[string]int32{
	"VOLUME_DEFAULT":     0,
	"VOLUME_TOMBSTONE":   1,
	"VOLUME_X_DELETE_AT": 2,
}

func (x VolumeType) String() string {
	return proto.EnumName(VolumeType_name, int32(x))
}

func (VolumeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{0}
}

// VolumeState state
type VolumeState int32

const (
	// Default state, volume can be read from and written to
	VolumeState_STATE_RW VolumeState = 0
	// Volume is being compacted (source). New objects cannot be appended
	VolumeState_STATE_COMPACTION_SRC VolumeState = 1
	// Volume is a compaction target. New objects cannot be appended
	VolumeState_STATE_COMPACTION_TARGET VolumeState = 2
)

var VolumeState_name = map[int32]string{
	0: "STATE_RW",
	1: "STATE_COMPACTION_SRC",
	2: "STATE_COMPACTION_TARGET",
}

var VolumeState_value = map[string]int32{
	"STATE_RW":                0,
	"STATE_COMPACTION_SRC":    1,
	"STATE_COMPACTION_TARGET": 2,
}

func (x VolumeState) String() string {
	return proto.EnumName(VolumeState_name, int32(x))
}

func (VolumeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{1}
}

type ListPartitionsInfo struct {
	PartitionBits        uint32   `protobuf:"varint,1,opt,name=partition_bits,json=partitionBits,proto3" json:"partition_bits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPartitionsInfo) Reset()         { *m = ListPartitionsInfo{} }
func (m *ListPartitionsInfo) String() string { return proto.CompactTextString(m) }
func (*ListPartitionsInfo) ProtoMessage()    {}
func (*ListPartitionsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{0}
}

func (m *ListPartitionsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPartitionsInfo.Unmarshal(m, b)
}
func (m *ListPartitionsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPartitionsInfo.Marshal(b, m, deterministic)
}
func (m *ListPartitionsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPartitionsInfo.Merge(m, src)
}
func (m *ListPartitionsInfo) XXX_Size() int {
	return xxx_messageInfo_ListPartitionsInfo.Size(m)
}
func (m *ListPartitionsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPartitionsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ListPartitionsInfo proto.InternalMessageInfo

func (m *ListPartitionsInfo) GetPartitionBits() uint32 {
	if m != nil {
		return m.PartitionBits
	}
	return 0
}

type ListPartitionInfo struct {
	Partition            uint32   `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	PartitionBits        uint32   `protobuf:"varint,2,opt,name=partition_bits,json=partitionBits,proto3" json:"partition_bits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPartitionInfo) Reset()         { *m = ListPartitionInfo{} }
func (m *ListPartitionInfo) String() string { return proto.CompactTextString(m) }
func (*ListPartitionInfo) ProtoMessage()    {}
func (*ListPartitionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{1}
}

func (m *ListPartitionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPartitionInfo.Unmarshal(m, b)
}
func (m *ListPartitionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPartitionInfo.Marshal(b, m, deterministic)
}
func (m *ListPartitionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPartitionInfo.Merge(m, src)
}
func (m *ListPartitionInfo) XXX_Size() int {
	return xxx_messageInfo_ListPartitionInfo.Size(m)
}
func (m *ListPartitionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPartitionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ListPartitionInfo proto.InternalMessageInfo

func (m *ListPartitionInfo) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ListPartitionInfo) GetPartitionBits() uint32 {
	if m != nil {
		return m.PartitionBits
	}
	return 0
}

type ListSuffixInfo struct {
	Partition            uint32   `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Suffix               []byte   `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	PartitionBits        uint32   `protobuf:"varint,3,opt,name=partition_bits,json=partitionBits,proto3" json:"partition_bits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSuffixInfo) Reset()         { *m = ListSuffixInfo{} }
func (m *ListSuffixInfo) String() string { return proto.CompactTextString(m) }
func (*ListSuffixInfo) ProtoMessage()    {}
func (*ListSuffixInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{2}
}

func (m *ListSuffixInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSuffixInfo.Unmarshal(m, b)
}
func (m *ListSuffixInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSuffixInfo.Marshal(b, m, deterministic)
}
func (m *ListSuffixInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSuffixInfo.Merge(m, src)
}
func (m *ListSuffixInfo) XXX_Size() int {
	return xxx_messageInfo_ListSuffixInfo.Size(m)
}
func (m *ListSuffixInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSuffixInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ListSuffixInfo proto.InternalMessageInfo

func (m *ListSuffixInfo) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ListSuffixInfo) GetSuffix() []byte {
	if m != nil {
		return m.Suffix
	}
	return nil
}

func (m *ListSuffixInfo) GetPartitionBits() uint32 {
	if m != nil {
		return m.PartitionBits
	}
	return 0
}

// Generic reply message for List* functions (listdir like)
type DirEntries struct {
	Entry                []string `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirEntries) Reset()         { *m = DirEntries{} }
func (m *DirEntries) String() string { return proto.CompactTextString(m) }
func (*DirEntries) ProtoMessage()    {}
func (*DirEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{3}
}

func (m *DirEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirEntries.Unmarshal(m, b)
}
func (m *DirEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirEntries.Marshal(b, m, deterministic)
}
func (m *DirEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirEntries.Merge(m, src)
}
func (m *DirEntries) XXX_Size() int {
	return xxx_messageInfo_DirEntries.Size(m)
}
func (m *DirEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_DirEntries.DiscardUnknown(m)
}

var xxx_messageInfo_DirEntries proto.InternalMessageInfo

func (m *DirEntries) GetEntry() []string {
	if m != nil {
		return m.Entry
	}
	return nil
}

type VolumeIndex struct {
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// List only quarantined files, if true
	Quarantined bool   `protobuf:"varint,2,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	PageToken   []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize    uint32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,5,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeIndex) Reset()         { *m = VolumeIndex{} }
func (m *VolumeIndex) String() string { return proto.CompactTextString(m) }
func (*VolumeIndex) ProtoMessage()    {}
func (*VolumeIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{4}
}

func (m *VolumeIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeIndex.Unmarshal(m, b)
}
func (m *VolumeIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeIndex.Marshal(b, m, deterministic)
}
func (m *VolumeIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeIndex.Merge(m, src)
}
func (m *VolumeIndex) XXX_Size() int {
	return xxx_messageInfo_VolumeIndex.Size(m)
}
func (m *VolumeIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeIndex.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeIndex proto.InternalMessageInfo

func (m *VolumeIndex) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *VolumeIndex) GetQuarantined() bool {
	if m != nil {
		return m.Quarantined
	}
	return false
}

func (m *VolumeIndex) GetPageToken() []byte {
	if m != nil {
		return m.PageToken
	}
	return nil
}

func (m *VolumeIndex) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *VolumeIndex) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

type Volume struct {
	VolumeIndex          uint32     `protobuf:"varint,1,opt,name=volume_index,json=volumeIndex,proto3" json:"volume_index,omitempty"`
	VolumeType           VolumeType `protobuf:"varint,2,opt,name=volume_type,json=volumeType,proto3,enum=filemgr.VolumeType" json:"volume_type,omitempty"`
	VolumeState          uint32     `protobuf:"varint,3,opt,name=volume_state,json=volumeState,proto3" json:"volume_state,omitempty"`
	Partition            uint32     `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	NextOffset           uint64     `protobuf:"varint,5,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{5}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetVolumeIndex() uint32 {
	if m != nil {
		return m.VolumeIndex
	}
	return 0
}

func (m *Volume) GetVolumeType() VolumeType {
	if m != nil {
		return m.VolumeType
	}
	return VolumeType_VOLUME_DEFAULT
}

func (m *Volume) GetVolumeState() uint32 {
	if m != nil {
		return m.VolumeState
	}
	return 0
}

func (m *Volume) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *Volume) GetNextOffset() uint64 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

// Similar to volume but we don't want to require the
// partition
type GetNextOffsetInfo struct {
	VolumeIndex uint32 `protobuf:"varint,1,opt,name=volume_index,json=volumeIndex,proto3" json:"volume_index,omitempty"`
	VolumeType  uint32 `protobuf:"varint,2,opt,name=volume_type,json=volumeType,proto3" json:"volume_type,omitempty"`
	VolumeState uint32 `protobuf:"varint,3,opt,name=volume_state,json=volumeState,proto3" json:"volume_state,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,4,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextOffsetInfo) Reset()         { *m = GetNextOffsetInfo{} }
func (m *GetNextOffsetInfo) String() string { return proto.CompactTextString(m) }
func (*GetNextOffsetInfo) ProtoMessage()    {}
func (*GetNextOffsetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{6}
}

func (m *GetNextOffsetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextOffsetInfo.Unmarshal(m, b)
}
func (m *GetNextOffsetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextOffsetInfo.Marshal(b, m, deterministic)
}
func (m *GetNextOffsetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextOffsetInfo.Merge(m, src)
}
func (m *GetNextOffsetInfo) XXX_Size() int {
	return xxx_messageInfo_GetNextOffsetInfo.Size(m)
}
func (m *GetNextOffsetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextOffsetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextOffsetInfo proto.InternalMessageInfo

func (m *GetNextOffsetInfo) GetVolumeIndex() uint32 {
	if m != nil {
		return m.VolumeIndex
	}
	return 0
}

func (m *GetNextOffsetInfo) GetVolumeType() uint32 {
	if m != nil {
		return m.VolumeType
	}
	return 0
}

func (m *GetNextOffsetInfo) GetVolumeState() uint32 {
	if m != nil {
		return m.VolumeState
	}
	return 0
}

func (m *GetNextOffsetInfo) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

type ListVolumesInfo struct {
	Partition uint32     `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Type      VolumeType `protobuf:"varint,2,opt,name=type,proto3,enum=filemgr.VolumeType" json:"type,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,3,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVolumesInfo) Reset()         { *m = ListVolumesInfo{} }
func (m *ListVolumesInfo) String() string { return proto.CompactTextString(m) }
func (*ListVolumesInfo) ProtoMessage()    {}
func (*ListVolumesInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{7}
}

func (m *ListVolumesInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVolumesInfo.Unmarshal(m, b)
}
func (m *ListVolumesInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVolumesInfo.Marshal(b, m, deterministic)
}
func (m *ListVolumesInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVolumesInfo.Merge(m, src)
}
func (m *ListVolumesInfo) XXX_Size() int {
	return xxx_messageInfo_ListVolumesInfo.Size(m)
}
func (m *ListVolumesInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVolumesInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ListVolumesInfo proto.InternalMessageInfo

func (m *ListVolumesInfo) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ListVolumesInfo) GetType() VolumeType {
	if m != nil {
		return m.Type
	}
	return VolumeType_VOLUME_DEFAULT
}

func (m *ListVolumesInfo) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

type Volumes struct {
	Volumes              []*Volume `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Volumes) Reset()         { *m = Volumes{} }
func (m *Volumes) String() string { return proto.CompactTextString(m) }
func (*Volumes) ProtoMessage()    {}
func (*Volumes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{8}
}

func (m *Volumes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volumes.Unmarshal(m, b)
}
func (m *Volumes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volumes.Marshal(b, m, deterministic)
}
func (m *Volumes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volumes.Merge(m, src)
}
func (m *Volumes) XXX_Size() int {
	return xxx_messageInfo_Volumes.Size(m)
}
func (m *Volumes) XXX_DiscardUnknown() {
	xxx_messageInfo_Volumes.DiscardUnknown(m)
}

var xxx_messageInfo_Volumes proto.InternalMessageInfo

func (m *Volumes) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

// The response message to GetNextOffset
type VolumeNextOffset struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeNextOffset) Reset()         { *m = VolumeNextOffset{} }
func (m *VolumeNextOffset) String() string { return proto.CompactTextString(m) }
func (*VolumeNextOffset) ProtoMessage()    {}
func (*VolumeNextOffset) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{9}
}

func (m *VolumeNextOffset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeNextOffset.Unmarshal(m, b)
}
func (m *VolumeNextOffset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeNextOffset.Marshal(b, m, deterministic)
}
func (m *VolumeNextOffset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeNextOffset.Merge(m, src)
}
func (m *VolumeNextOffset) XXX_Size() int {
	return xxx_messageInfo_VolumeNextOffset.Size(m)
}
func (m *VolumeNextOffset) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeNextOffset.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeNextOffset proto.InternalMessageInfo

func (m *VolumeNextOffset) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// The request message for a new volume
type NewVolumeInfo struct {
	// Swift partition
	Partition uint32     `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Type      VolumeType `protobuf:"varint,2,opt,name=type,proto3,enum=filemgr.VolumeType" json:"type,omitempty"`
	// Index number of the volume. It is up to the client to map this to an actual filename.
	VolumeIndex uint32 `protobuf:"varint,3,opt,name=volume_index,json=volumeIndex,proto3" json:"volume_index,omitempty"`
	// Next available offset to use in the volume.
	Offset uint64      `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	State  VolumeState `protobuf:"varint,5,opt,name=state,proto3,enum=filemgr.VolumeState" json:"state,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,6,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewVolumeInfo) Reset()         { *m = NewVolumeInfo{} }
func (m *NewVolumeInfo) String() string { return proto.CompactTextString(m) }
func (*NewVolumeInfo) ProtoMessage()    {}
func (*NewVolumeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{10}
}

func (m *NewVolumeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewVolumeInfo.Unmarshal(m, b)
}
func (m *NewVolumeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewVolumeInfo.Marshal(b, m, deterministic)
}
func (m *NewVolumeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewVolumeInfo.Merge(m, src)
}
func (m *NewVolumeInfo) XXX_Size() int {
	return xxx_messageInfo_NewVolumeInfo.Size(m)
}
func (m *NewVolumeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewVolumeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NewVolumeInfo proto.InternalMessageInfo

func (m *NewVolumeInfo) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *NewVolumeInfo) GetType() VolumeType {
	if m != nil {
		return m.Type
	}
	return VolumeType_VOLUME_DEFAULT
}

func (m *NewVolumeInfo) GetVolumeIndex() uint32 {
	if m != nil {
		return m.VolumeIndex
	}
	return 0
}

func (m *NewVolumeInfo) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *NewVolumeInfo) GetState() VolumeState {
	if m != nil {
		return m.State
	}
	return VolumeState_STATE_RW
}

func (m *NewVolumeInfo) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

type NewVolumeState struct {
	VolumeIndex uint32      `protobuf:"varint,1,opt,name=volume_index,json=volumeIndex,proto3" json:"volume_index,omitempty"`
	State       VolumeState `protobuf:"varint,2,opt,name=state,proto3,enum=filemgr.VolumeState" json:"state,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,3,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewVolumeState) Reset()         { *m = NewVolumeState{} }
func (m *NewVolumeState) String() string { return proto.CompactTextString(m) }
func (*NewVolumeState) ProtoMessage()    {}
func (*NewVolumeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{11}
}

func (m *NewVolumeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewVolumeState.Unmarshal(m, b)
}
func (m *NewVolumeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewVolumeState.Marshal(b, m, deterministic)
}
func (m *NewVolumeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewVolumeState.Merge(m, src)
}
func (m *NewVolumeState) XXX_Size() int {
	return xxx_messageInfo_NewVolumeState.Size(m)
}
func (m *NewVolumeState) XXX_DiscardUnknown() {
	xxx_messageInfo_NewVolumeState.DiscardUnknown(m)
}

var xxx_messageInfo_NewVolumeState proto.InternalMessageInfo

func (m *NewVolumeState) GetVolumeIndex() uint32 {
	if m != nil {
		return m.VolumeIndex
	}
	return 0
}

func (m *NewVolumeState) GetState() VolumeState {
	if m != nil {
		return m.State
	}
	return VolumeState_STATE_RW
}

func (m *NewVolumeState) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

// The response message for a new volume
type NewVolumeReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewVolumeReply) Reset()         { *m = NewVolumeReply{} }
func (m *NewVolumeReply) String() string { return proto.CompactTextString(m) }
func (*NewVolumeReply) ProtoMessage()    {}
func (*NewVolumeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{12}
}

func (m *NewVolumeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewVolumeReply.Unmarshal(m, b)
}
func (m *NewVolumeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewVolumeReply.Marshal(b, m, deterministic)
}
func (m *NewVolumeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewVolumeReply.Merge(m, src)
}
func (m *NewVolumeReply) XXX_Size() int {
	return xxx_messageInfo_NewVolumeReply.Size(m)
}
func (m *NewVolumeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewVolumeReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewVolumeReply proto.InternalMessageInfo

type DelObjectReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelObjectReply) Reset()         { *m = DelObjectReply{} }
func (m *DelObjectReply) String() string { return proto.CompactTextString(m) }
func (*DelObjectReply) ProtoMessage()    {}
func (*DelObjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{13}
}

func (m *DelObjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelObjectReply.Unmarshal(m, b)
}
func (m *DelObjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelObjectReply.Marshal(b, m, deterministic)
}
func (m *DelObjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelObjectReply.Merge(m, src)
}
func (m *DelObjectReply) XXX_Size() int {
	return xxx_messageInfo_DelObjectReply.Size(m)
}
func (m *DelObjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DelObjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_DelObjectReply proto.InternalMessageInfo

type RenameReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameReply) Reset()         { *m = RenameReply{} }
func (m *RenameReply) String() string { return proto.CompactTextString(m) }
func (*RenameReply) ProtoMessage()    {}
func (*RenameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{14}
}

func (m *RenameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameReply.Unmarshal(m, b)
}
func (m *RenameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameReply.Marshal(b, m, deterministic)
}
func (m *RenameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameReply.Merge(m, src)
}
func (m *RenameReply) XXX_Size() int {
	return xxx_messageInfo_RenameReply.Size(m)
}
func (m *RenameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameReply.DiscardUnknown(m)
}

var xxx_messageInfo_RenameReply proto.InternalMessageInfo

// The request message for a new object
type NewObjectInfo struct {
	// Object "name". Name made of (md5, timestamp, etc..)
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Index number of the volume.
	VolumeIndex uint32 `protobuf:"varint,2,opt,name=volume_index,json=volumeIndex,proto3" json:"volume_index,omitempty"`
	// Start offset of the object in the volume.
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Next available offset to use in the volume.
	NextOffset uint64 `protobuf:"varint,4,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,5,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewObjectInfo) Reset()         { *m = NewObjectInfo{} }
func (m *NewObjectInfo) String() string { return proto.CompactTextString(m) }
func (*NewObjectInfo) ProtoMessage()    {}
func (*NewObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{15}
}

func (m *NewObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewObjectInfo.Unmarshal(m, b)
}
func (m *NewObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewObjectInfo.Marshal(b, m, deterministic)
}
func (m *NewObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewObjectInfo.Merge(m, src)
}
func (m *NewObjectInfo) XXX_Size() int {
	return xxx_messageInfo_NewObjectInfo.Size(m)
}
func (m *NewObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NewObjectInfo proto.InternalMessageInfo

func (m *NewObjectInfo) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *NewObjectInfo) GetVolumeIndex() uint32 {
	if m != nil {
		return m.VolumeIndex
	}
	return 0
}

func (m *NewObjectInfo) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *NewObjectInfo) GetNextOffset() uint64 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

func (m *NewObjectInfo) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

// The response message for a new object
// Currently empty, but we may want to return something in the future
type NewObjectReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewObjectReply) Reset()         { *m = NewObjectReply{} }
func (m *NewObjectReply) String() string { return proto.CompactTextString(m) }
func (*NewObjectReply) ProtoMessage()    {}
func (*NewObjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{16}
}

func (m *NewObjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewObjectReply.Unmarshal(m, b)
}
func (m *NewObjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewObjectReply.Marshal(b, m, deterministic)
}
func (m *NewObjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewObjectReply.Merge(m, src)
}
func (m *NewObjectReply) XXX_Size() int {
	return xxx_messageInfo_NewObjectReply.Size(m)
}
func (m *NewObjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewObjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewObjectReply proto.InternalMessageInfo

type QuarantinedObjectName struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuarantinedObjectName) Reset()         { *m = QuarantinedObjectName{} }
func (m *QuarantinedObjectName) String() string { return proto.CompactTextString(m) }
func (*QuarantinedObjectName) ProtoMessage()    {}
func (*QuarantinedObjectName) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{17}
}

func (m *QuarantinedObjectName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuarantinedObjectName.Unmarshal(m, b)
}
func (m *QuarantinedObjectName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuarantinedObjectName.Marshal(b, m, deterministic)
}
func (m *QuarantinedObjectName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuarantinedObjectName.Merge(m, src)
}
func (m *QuarantinedObjectName) XXX_Size() int {
	return xxx_messageInfo_QuarantinedObjectName.Size(m)
}
func (m *QuarantinedObjectName) XXX_DiscardUnknown() {
	xxx_messageInfo_QuarantinedObjectName.DiscardUnknown(m)
}

var xxx_messageInfo_QuarantinedObjectName proto.InternalMessageInfo

func (m *QuarantinedObjectName) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type QuarantinedObjectNames struct {
	Objects              []*QuarantinedObjectName `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	NextPageToken        []byte                   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *QuarantinedObjectNames) Reset()         { *m = QuarantinedObjectNames{} }
func (m *QuarantinedObjectNames) String() string { return proto.CompactTextString(m) }
func (*QuarantinedObjectNames) ProtoMessage()    {}
func (*QuarantinedObjectNames) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{18}
}

func (m *QuarantinedObjectNames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuarantinedObjectNames.Unmarshal(m, b)
}
func (m *QuarantinedObjectNames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuarantinedObjectNames.Marshal(b, m, deterministic)
}
func (m *QuarantinedObjectNames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuarantinedObjectNames.Merge(m, src)
}
func (m *QuarantinedObjectNames) XXX_Size() int {
	return xxx_messageInfo_QuarantinedObjectNames.Size(m)
}
func (m *QuarantinedObjectNames) XXX_DiscardUnknown() {
	xxx_messageInfo_QuarantinedObjectNames.DiscardUnknown(m)
}

var xxx_messageInfo_QuarantinedObjectNames proto.InternalMessageInfo

func (m *QuarantinedObjectNames) GetObjects() []*QuarantinedObjectName {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *QuarantinedObjectNames) GetNextPageToken() []byte {
	if m != nil {
		return m.NextPageToken
	}
	return nil
}

type ObjectName struct {
	// name of the object.
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,2,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectName) Reset()         { *m = ObjectName{} }
func (m *ObjectName) String() string { return proto.CompactTextString(m) }
func (*ObjectName) ProtoMessage()    {}
func (*ObjectName) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{19}
}

func (m *ObjectName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectName.Unmarshal(m, b)
}
func (m *ObjectName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectName.Marshal(b, m, deterministic)
}
func (m *ObjectName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectName.Merge(m, src)
}
func (m *ObjectName) XXX_Size() int {
	return xxx_messageInfo_ObjectName.Size(m)
}
func (m *ObjectName) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectName.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectName proto.InternalMessageInfo

func (m *ObjectName) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ObjectName) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

type LoadObjectInfo struct {
	// name of the object.
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Is it quarantined ?
	IsQuarantined bool `protobuf:"varint,2,opt,name=is_quarantined,json=isQuarantined,proto3" json:"is_quarantined,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,5,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadObjectInfo) Reset()         { *m = LoadObjectInfo{} }
func (m *LoadObjectInfo) String() string { return proto.CompactTextString(m) }
func (*LoadObjectInfo) ProtoMessage()    {}
func (*LoadObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{20}
}

func (m *LoadObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadObjectInfo.Unmarshal(m, b)
}
func (m *LoadObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadObjectInfo.Marshal(b, m, deterministic)
}
func (m *LoadObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadObjectInfo.Merge(m, src)
}
func (m *LoadObjectInfo) XXX_Size() int {
	return xxx_messageInfo_LoadObjectInfo.Size(m)
}
func (m *LoadObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoadObjectInfo proto.InternalMessageInfo

func (m *LoadObjectInfo) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *LoadObjectInfo) GetIsQuarantined() bool {
	if m != nil {
		return m.IsQuarantined
	}
	return false
}

func (m *LoadObjectInfo) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

// The request message to rename an object
type RenameInfo struct {
	// name of the object.
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// new name of the object
	NewName []byte `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,3,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameInfo) Reset()         { *m = RenameInfo{} }
func (m *RenameInfo) String() string { return proto.CompactTextString(m) }
func (*RenameInfo) ProtoMessage()    {}
func (*RenameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{21}
}

func (m *RenameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameInfo.Unmarshal(m, b)
}
func (m *RenameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameInfo.Marshal(b, m, deterministic)
}
func (m *RenameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameInfo.Merge(m, src)
}
func (m *RenameInfo) XXX_Size() int {
	return xxx_messageInfo_RenameInfo.Size(m)
}
func (m *RenameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RenameInfo proto.InternalMessageInfo

func (m *RenameInfo) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RenameInfo) GetNewName() []byte {
	if m != nil {
		return m.NewName
	}
	return nil
}

func (m *RenameInfo) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

type Object struct {
	// name of the object.
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Index number of the volume.
	VolumeIndex uint32 `protobuf:"varint,2,opt,name=volume_index,json=volumeIndex,proto3" json:"volume_index,omitempty"`
	// Start offset of the object in the volume.
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{22}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Object) GetVolumeIndex() uint32 {
	if m != nil {
		return m.VolumeIndex
	}
	return 0
}

func (m *Object) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type LoadObjectsResponse struct {
	Objects              []*Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	NextPageToken        []byte    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoadObjectsResponse) Reset()         { *m = LoadObjectsResponse{} }
func (m *LoadObjectsResponse) String() string { return proto.CompactTextString(m) }
func (*LoadObjectsResponse) ProtoMessage()    {}
func (*LoadObjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{23}
}

func (m *LoadObjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadObjectsResponse.Unmarshal(m, b)
}
func (m *LoadObjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadObjectsResponse.Marshal(b, m, deterministic)
}
func (m *LoadObjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadObjectsResponse.Merge(m, src)
}
func (m *LoadObjectsResponse) XXX_Size() int {
	return xxx_messageInfo_LoadObjectsResponse.Size(m)
}
func (m *LoadObjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadObjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadObjectsResponse proto.InternalMessageInfo

func (m *LoadObjectsResponse) GetObjects() []*Object {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *LoadObjectsResponse) GetNextPageToken() []byte {
	if m != nil {
		return m.NextPageToken
	}
	return nil
}

type ObjectPrefix struct {
	Prefix []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Is this request coming from a repair tool ?
	RepairTool           bool     `protobuf:"varint,2,opt,name=repair_tool,json=repairTool,proto3" json:"repair_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPrefix) Reset()         { *m = ObjectPrefix{} }
func (m *ObjectPrefix) String() string { return proto.CompactTextString(m) }
func (*ObjectPrefix) ProtoMessage()    {}
func (*ObjectPrefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{24}
}

func (m *ObjectPrefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPrefix.Unmarshal(m, b)
}
func (m *ObjectPrefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPrefix.Marshal(b, m, deterministic)
}
func (m *ObjectPrefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPrefix.Merge(m, src)
}
func (m *ObjectPrefix) XXX_Size() int {
	return xxx_messageInfo_ObjectPrefix.Size(m)
}
func (m *ObjectPrefix) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPrefix.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPrefix proto.InternalMessageInfo

func (m *ObjectPrefix) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *ObjectPrefix) GetRepairTool() bool {
	if m != nil {
		return m.RepairTool
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{25}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetStatsInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsInfo) Reset()         { *m = GetStatsInfo{} }
func (m *GetStatsInfo) String() string { return proto.CompactTextString(m) }
func (*GetStatsInfo) ProtoMessage()    {}
func (*GetStatsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{26}
}

func (m *GetStatsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsInfo.Unmarshal(m, b)
}
func (m *GetStatsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsInfo.Marshal(b, m, deterministic)
}
func (m *GetStatsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsInfo.Merge(m, src)
}
func (m *GetStatsInfo) XXX_Size() int {
	return xxx_messageInfo_GetStatsInfo.Size(m)
}
func (m *GetStatsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsInfo proto.InternalMessageInfo

type PartitionContent struct {
	FileEntries          []*FullPathEntry `protobuf:"bytes,1,rep,name=file_entries,json=fileEntries,proto3" json:"file_entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PartitionContent) Reset()         { *m = PartitionContent{} }
func (m *PartitionContent) String() string { return proto.CompactTextString(m) }
func (*PartitionContent) ProtoMessage()    {}
func (*PartitionContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{27}
}

func (m *PartitionContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionContent.Unmarshal(m, b)
}
func (m *PartitionContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionContent.Marshal(b, m, deterministic)
}
func (m *PartitionContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionContent.Merge(m, src)
}
func (m *PartitionContent) XXX_Size() int {
	return xxx_messageInfo_PartitionContent.Size(m)
}
func (m *PartitionContent) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionContent.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionContent proto.InternalMessageInfo

func (m *PartitionContent) GetFileEntries() []*FullPathEntry {
	if m != nil {
		return m.FileEntries
	}
	return nil
}

type FullPathEntry struct {
	// We could add the partition if needed
	Suffix               []byte   `protobuf:"bytes,1,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Ohash                []byte   `protobuf:"bytes,2,opt,name=ohash,proto3" json:"ohash,omitempty"`
	Filename             []byte   `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullPathEntry) Reset()         { *m = FullPathEntry{} }
func (m *FullPathEntry) String() string { return proto.CompactTextString(m) }
func (*FullPathEntry) ProtoMessage()    {}
func (*FullPathEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{28}
}

func (m *FullPathEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullPathEntry.Unmarshal(m, b)
}
func (m *FullPathEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullPathEntry.Marshal(b, m, deterministic)
}
func (m *FullPathEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullPathEntry.Merge(m, src)
}
func (m *FullPathEntry) XXX_Size() int {
	return xxx_messageInfo_FullPathEntry.Size(m)
}
func (m *FullPathEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FullPathEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FullPathEntry proto.InternalMessageInfo

func (m *FullPathEntry) GetSuffix() []byte {
	if m != nil {
		return m.Suffix
	}
	return nil
}

func (m *FullPathEntry) GetOhash() []byte {
	if m != nil {
		return m.Ohash
	}
	return nil
}

func (m *FullPathEntry) GetFilename() []byte {
	if m != nil {
		return m.Filename
	}
	return nil
}

type KvState struct {
	IsClean              bool     `protobuf:"varint,1,opt,name=isClean,proto3" json:"isClean,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KvState) Reset()         { *m = KvState{} }
func (m *KvState) String() string { return proto.CompactTextString(m) }
func (*KvState) ProtoMessage()    {}
func (*KvState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{29}
}

func (m *KvState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvState.Unmarshal(m, b)
}
func (m *KvState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvState.Marshal(b, m, deterministic)
}
func (m *KvState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvState.Merge(m, src)
}
func (m *KvState) XXX_Size() int {
	return xxx_messageInfo_KvState.Size(m)
}
func (m *KvState) XXX_DiscardUnknown() {
	xxx_messageInfo_KvState.DiscardUnknown(m)
}

var xxx_messageInfo_KvState proto.InternalMessageInfo

func (m *KvState) GetIsClean() bool {
	if m != nil {
		return m.IsClean
	}
	return false
}

// KV stats
type KVStats struct {
	Stats                map[string]uint64 `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *KVStats) Reset()         { *m = KVStats{} }
func (m *KVStats) String() string { return proto.CompactTextString(m) }
func (*KVStats) ProtoMessage()    {}
func (*KVStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{30}
}

func (m *KVStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVStats.Unmarshal(m, b)
}
func (m *KVStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVStats.Marshal(b, m, deterministic)
}
func (m *KVStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVStats.Merge(m, src)
}
func (m *KVStats) XXX_Size() int {
	return xxx_messageInfo_KVStats.Size(m)
}
func (m *KVStats) XXX_DiscardUnknown() {
	xxx_messageInfo_KVStats.DiscardUnknown(m)
}

var xxx_messageInfo_KVStats proto.InternalMessageInfo

func (m *KVStats) GetStats() map[string]uint64 {
	if m != nil {
		return m.Stats
	}
	return nil
}

type ListQuarantinedOHashesInfo struct {
	PageToken            []byte   `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuarantinedOHashesInfo) Reset()         { *m = ListQuarantinedOHashesInfo{} }
func (m *ListQuarantinedOHashesInfo) String() string { return proto.CompactTextString(m) }
func (*ListQuarantinedOHashesInfo) ProtoMessage()    {}
func (*ListQuarantinedOHashesInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcd0776e05e82a6, []int{31}
}

func (m *ListQuarantinedOHashesInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuarantinedOHashesInfo.Unmarshal(m, b)
}
func (m *ListQuarantinedOHashesInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuarantinedOHashesInfo.Marshal(b, m, deterministic)
}
func (m *ListQuarantinedOHashesInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuarantinedOHashesInfo.Merge(m, src)
}
func (m *ListQuarantinedOHashesInfo) XXX_Size() int {
	return xxx_messageInfo_ListQuarantinedOHashesInfo.Size(m)
}
func (m *ListQuarantinedOHashesInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuarantinedOHashesInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuarantinedOHashesInfo proto.InternalMessageInfo

func (m *ListQuarantinedOHashesInfo) GetPageToken() []byte {
	if m != nil {
		return m.PageToken
	}
	return nil
}

func (m *ListQuarantinedOHashesInfo) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func init() {
	proto.RegisterEnum("filemgr.VolumeType", VolumeType_name, VolumeType_value)
	proto.RegisterEnum("filemgr.VolumeState", VolumeState_name, VolumeState_value)
	proto.RegisterType((*ListPartitionsInfo)(nil), "filemgr.ListPartitionsInfo")
	proto.RegisterType((*ListPartitionInfo)(nil), "filemgr.ListPartitionInfo")
	proto.RegisterType((*ListSuffixInfo)(nil), "filemgr.ListSuffixInfo")
	proto.RegisterType((*DirEntries)(nil), "filemgr.DirEntries")
	proto.RegisterType((*VolumeIndex)(nil), "filemgr.VolumeIndex")
	proto.RegisterType((*Volume)(nil), "filemgr.Volume")
	proto.RegisterType((*GetNextOffsetInfo)(nil), "filemgr.GetNextOffsetInfo")
	proto.RegisterType((*ListVolumesInfo)(nil), "filemgr.ListVolumesInfo")
	proto.RegisterType((*Volumes)(nil), "filemgr.Volumes")
	proto.RegisterType((*VolumeNextOffset)(nil), "filemgr.VolumeNextOffset")
	proto.RegisterType((*NewVolumeInfo)(nil), "filemgr.NewVolumeInfo")
	proto.RegisterType((*NewVolumeState)(nil), "filemgr.NewVolumeState")
	proto.RegisterType((*NewVolumeReply)(nil), "filemgr.NewVolumeReply")
	proto.RegisterType((*DelObjectReply)(nil), "filemgr.DelObjectReply")
	proto.RegisterType((*RenameReply)(nil), "filemgr.RenameReply")
	proto.RegisterType((*NewObjectInfo)(nil), "filemgr.NewObjectInfo")
	proto.RegisterType((*NewObjectReply)(nil), "filemgr.NewObjectReply")
	proto.RegisterType((*QuarantinedObjectName)(nil), "filemgr.QuarantinedObjectName")
	proto.RegisterType((*QuarantinedObjectNames)(nil), "filemgr.QuarantinedObjectNames")
	proto.RegisterType((*ObjectName)(nil), "filemgr.ObjectName")
	proto.RegisterType((*LoadObjectInfo)(nil), "filemgr.LoadObjectInfo")
	proto.RegisterType((*RenameInfo)(nil), "filemgr.RenameInfo")
	proto.RegisterType((*Object)(nil), "filemgr.Object")
	proto.RegisterType((*LoadObjectsResponse)(nil), "filemgr.LoadObjectsResponse")
	proto.RegisterType((*ObjectPrefix)(nil), "filemgr.ObjectPrefix")
	proto.RegisterType((*Empty)(nil), "filemgr.Empty")
	proto.RegisterType((*GetStatsInfo)(nil), "filemgr.GetStatsInfo")
	proto.RegisterType((*PartitionContent)(nil), "filemgr.PartitionContent")
	proto.RegisterType((*FullPathEntry)(nil), "filemgr.FullPathEntry")
	proto.RegisterType((*KvState)(nil), "filemgr.KvState")
	proto.RegisterType((*KVStats)(nil), "filemgr.KVStats")
	proto.RegisterMapType((map[string]uint64)(nil), "filemgr.KVStats.StatsEntry")
	proto.RegisterType((*ListQuarantinedOHashesInfo)(nil), "filemgr.ListQuarantinedOHashesInfo")
}

func init() { proto.RegisterFile("fmgr.proto", fileDescriptor_1fcd0776e05e82a6) }

var fileDescriptor_1fcd0776e05e82a6 = []byte{
	// 1037 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x46, 0xb6, 0xfc, 0x93, 0xe3, 0x9f, 0xb8, 0xdb, 0x10, 0x4c, 0x02, 0xb4, 0x88, 0x01, 0x4a,
	0x98, 0xc9, 0x0c, 0xa5, 0x17, 0x01, 0xae, 0x5c, 0xc7, 0x0d, 0x19, 0x12, 0xdb, 0xac, 0xd5, 0xb4,
	0xcc, 0x30, 0xa3, 0x51, 0xc8, 0x3a, 0x11, 0x55, 0x24, 0x21, 0xad, 0xdd, 0xb8, 0x57, 0xbc, 0x07,
	0x37, 0x0c, 0xaf, 0xc2, 0x7b, 0xf0, 0x2c, 0xec, 0x9f, 0x64, 0x59, 0x72, 0x63, 0x67, 0xa6, 0x37,
	0x9e, 0x3d, 0xdf, 0x1e, 0x9d, 0xfd, 0xbe, 0x73, 0x8e, 0x77, 0x0f, 0xc0, 0xf8, 0xfa, 0x32, 0xdc,
	0x0f, 0x42, 0x9f, 0xfa, 0xa8, 0x32, 0x76, 0x5c, 0xc2, 0x4c, 0xe3, 0x07, 0x40, 0x27, 0x4e, 0x44,
	0x87, 0x76, 0x48, 0x1d, 0xea, 0xf8, 0x5e, 0x74, 0xec, 0x8d, 0x7d, 0xf4, 0x39, 0x34, 0x83, 0x18,
	0xb1, 0xce, 0x1d, 0x1a, 0xb5, 0xb5, 0x87, 0xda, 0xa3, 0x06, 0x6e, 0x24, 0xe8, 0x53, 0x06, 0x1a,
	0x2f, 0xe1, 0xde, 0xc2, 0xc7, 0xe2, 0xdb, 0x8f, 0x60, 0x23, 0xf1, 0x52, 0x9f, 0xcd, 0x81, 0x25,
	0x91, 0x0b, 0xcb, 0x22, 0x5f, 0x43, 0x93, 0x47, 0x1e, 0x4d, 0xc6, 0x63, 0xe7, 0x66, 0x8d, 0xb0,
	0xdb, 0x50, 0x8e, 0x84, 0xaf, 0x08, 0x57, 0xc7, 0xca, 0x5a, 0x72, 0x5c, 0x71, 0xd9, 0x71, 0x06,
	0xc0, 0xa1, 0x13, 0xf6, 0x3c, 0x1a, 0x3a, 0x24, 0x42, 0x5b, 0x50, 0x22, 0x6c, 0x39, 0x63, 0xc7,
	0x14, 0x1f, 0x6d, 0x60, 0x69, 0x18, 0xff, 0x68, 0x50, 0x3b, 0xf3, 0xdd, 0xc9, 0x35, 0x39, 0xf6,
	0x2e, 0xc8, 0x0d, 0xf7, 0x72, 0xf8, 0x42, 0x91, 0x91, 0x06, 0x7a, 0x08, 0xb5, 0x3f, 0x26, 0x76,
	0x68, 0x7b, 0xd4, 0xf1, 0xc8, 0x85, 0x60, 0x53, 0xc5, 0x69, 0x08, 0x7d, 0x0c, 0x10, 0xd8, 0x97,
	0xc4, 0xa2, 0xfe, 0x2b, 0xe2, 0x09, 0x3a, 0x75, 0xae, 0xe4, 0x92, 0x98, 0x1c, 0x40, 0xbb, 0x20,
	0x0c, 0x2b, 0x72, 0xde, 0x90, 0xb6, 0x2e, 0x42, 0x57, 0x39, 0x30, 0x62, 0x36, 0x7a, 0x00, 0xb5,
	0x90, 0x04, 0xb6, 0x13, 0xb2, 0xaf, 0x7d, 0xb7, 0x5d, 0x12, 0xd1, 0x41, 0x42, 0x26, 0x43, 0x8c,
	0x7f, 0x35, 0x28, 0x4b, 0x92, 0xe8, 0x53, 0xa8, 0x4f, 0xc5, 0xca, 0x4a, 0xd3, 0xac, 0x4d, 0x53,
	0x12, 0x9e, 0x80, 0x32, 0x2d, 0x3a, 0x0b, 0x88, 0x20, 0xdb, 0x7c, 0x7c, 0x7f, 0x5f, 0xf5, 0xc6,
	0xbe, 0x0c, 0x64, 0xb2, 0x2d, 0x0c, 0xd3, 0x64, 0x9d, 0x0a, 0x1c, 0x51, 0x9b, 0x12, 0x95, 0x51,
	0x15, 0x69, 0xc4, 0xa1, 0xc5, 0x62, 0xe9, 0xd9, 0x62, 0x31, 0x15, 0x1e, 0xb9, 0xa1, 0x96, 0x3f,
	0x1e, 0x47, 0x84, 0x0a, 0x15, 0x3a, 0x06, 0x0e, 0x0d, 0x04, 0x62, 0xfc, 0xa5, 0xc1, 0xbd, 0x23,
	0x42, 0xfb, 0x09, 0x22, 0x3a, 0x60, 0x0d, 0x41, 0x0f, 0xf2, 0x82, 0x1a, 0x77, 0xe5, 0x9e, 0xc9,
	0xb1, 0x9e, 0xcb, 0xf1, 0x0c, 0x36, 0x79, 0x6f, 0xca, 0xec, 0x44, 0x6b, 0x34, 0xe7, 0x97, 0xa0,
	0xaf, 0xca, 0xaf, 0x70, 0xc8, 0x1e, 0x5d, 0xcc, 0x1d, 0xfd, 0x04, 0x2a, 0xea, 0x58, 0xf4, 0x15,
	0x54, 0x24, 0xeb, 0x48, 0xb4, 0x69, 0xed, 0xf1, 0x66, 0x26, 0x2e, 0x8e, 0xf7, 0x8d, 0x3d, 0x68,
	0x49, 0x68, 0x9e, 0x50, 0xfe, 0x87, 0x51, 0xe9, 0xd7, 0x44, 0xfa, 0x95, 0x65, 0xfc, 0xa7, 0x41,
	0xa3, 0x4f, 0x5e, 0xc7, 0x8d, 0xfe, 0xee, 0xb4, 0x65, 0xab, 0x57, 0xcc, 0x57, 0x6f, 0xce, 0x49,
	0x4f, 0x73, 0x42, 0x7b, 0x50, 0x92, 0xd5, 0x2a, 0x89, 0x43, 0xb6, 0x32, 0x87, 0x88, 0xb2, 0x61,
	0xe9, 0x92, 0x4d, 0x61, 0x39, 0x97, 0xc2, 0x3f, 0x35, 0x68, 0x26, 0x02, 0x65, 0xc5, 0xd7, 0x68,
	0xac, 0x84, 0x42, 0xe1, 0xce, 0x14, 0xf2, 0x55, 0x6c, 0xa5, 0x18, 0x60, 0x12, 0xb8, 0x33, 0x8e,
	0x1c, 0x12, 0x77, 0x70, 0xfe, 0x3b, 0xf9, 0x8d, 0x4a, 0xa4, 0x01, 0x35, 0x4c, 0x3c, 0x3b, 0x76,
	0xf8, 0x5b, 0x96, 0x45, 0x7a, 0x88, 0xb2, 0x20, 0xd0, 0xf9, 0xb6, 0x20, 0x5b, 0xc7, 0x62, 0x9d,
	0x13, 0x52, 0xb8, 0x2d, 0xc7, 0xc5, 0x85, 0x1c, 0x67, 0xfe, 0x93, 0x7a, 0xf6, 0x3f, 0xb9, 0xfa,
	0xea, 0x91, 0xaa, 0xd2, 0x1a, 0xbe, 0x86, 0xf7, 0x7f, 0x9e, 0x5f, 0x7c, 0x72, 0xa7, 0xcf, 0x79,
	0x2e, 0xe1, 0x6e, 0xbc, 0x81, 0xed, 0xa5, 0xce, 0x11, 0x3a, 0x80, 0x8a, 0x2f, 0xcc, 0xb8, 0xd3,
	0x3f, 0x49, 0xb2, 0xbf, 0xf4, 0x0b, 0x1c, 0xbb, 0xa3, 0x2f, 0x60, 0x53, 0x88, 0x4a, 0xdd, 0xb7,
	0xf2, 0x79, 0x68, 0x70, 0x78, 0x18, 0xdf, 0xb9, 0x46, 0x07, 0xe0, 0x76, 0x76, 0x59, 0xf5, 0x85,
	0x9c, 0x7a, 0x97, 0x3d, 0x58, 0xbe, 0x7d, 0xb1, 0xa2, 0x40, 0xec, 0x39, 0x72, 0x22, 0x2b, 0xff,
	0x40, 0x34, 0x9c, 0x28, 0x25, 0x65, 0x75, 0xae, 0x7f, 0x05, 0x90, 0xdd, 0xf1, 0xd6, 0x93, 0x3e,
	0x84, 0xaa, 0x47, 0x5e, 0x5b, 0x02, 0x97, 0x9a, 0x2b, 0xcc, 0xee, 0x2f, 0xd1, 0x92, 0xef, 0xcf,
	0x17, 0x50, 0x96, 0x3a, 0xde, 0x71, 0x93, 0x19, 0x57, 0x70, 0x7f, 0x9e, 0xa4, 0x08, 0x93, 0x28,
	0x60, 0x03, 0x07, 0xe1, 0x57, 0xd9, 0x62, 0x81, 0xe7, 0x57, 0x99, 0x6a, 0xa7, 0x3b, 0x57, 0xf4,
	0x08, 0xea, 0xf2, 0xd3, 0x61, 0x48, 0xf8, 0x1c, 0xc0, 0x18, 0x05, 0x62, 0xa5, 0xa4, 0x28, 0x6b,
	0x75, 0x5d, 0x2b, 0x50, 0xea, 0x5d, 0x07, 0x74, 0x66, 0x34, 0xa1, 0xce, 0x9e, 0x24, 0xfe, 0x47,
	0x17, 0x57, 0xbe, 0x71, 0x0a, 0xad, 0x64, 0xee, 0xe9, 0xfa, 0x1e, 0x65, 0x43, 0x02, 0xfa, 0x0e,
	0xea, 0x9c, 0xb8, 0x45, 0xe4, 0x20, 0xa1, 0xd4, 0x6c, 0x27, 0x6a, 0x9e, 0x4d, 0x5c, 0x77, 0x68,
	0xd3, 0x2b, 0x3e, 0x68, 0xcc, 0x70, 0x8d, 0xc3, 0x6a, 0xe6, 0x30, 0x7e, 0x81, 0xc6, 0xc2, 0x6e,
	0x6a, 0xa2, 0xd1, 0x16, 0x26, 0x1a, 0x36, 0x76, 0xf8, 0x57, 0x76, 0x74, 0xa5, 0x74, 0x4b, 0x03,
	0xed, 0x40, 0x95, 0x47, 0x13, 0xc5, 0x92, 0x23, 0x45, 0x62, 0x1b, 0x9f, 0x41, 0xe5, 0xa7, 0xa9,
	0xbc, 0xe9, 0xda, 0x50, 0x71, 0xa2, 0xae, 0x4b, 0x6c, 0x79, 0x93, 0x57, 0x71, 0x6c, 0x1a, 0x53,
	0xe6, 0x74, 0x26, 0xd4, 0xa1, 0x6f, 0xe4, 0x5d, 0x17, 0xd3, 0xdf, 0x4d, 0xe8, 0x2b, 0x87, 0x7d,
	0xf1, 0x2b, 0x35, 0x48, 0xcf, 0x9d, 0x03, 0x80, 0x39, 0x88, 0x5a, 0x50, 0x7c, 0x45, 0x66, 0xe2,
	0x84, 0x0d, 0xcc, 0x97, 0x9c, 0xf4, 0xd4, 0x76, 0x27, 0xb2, 0x15, 0x75, 0x2c, 0x8d, 0xef, 0x0b,
	0x07, 0x1a, 0x1b, 0x21, 0x77, 0xf8, 0x63, 0x9a, 0xfe, 0x23, 0xff, 0xc8, 0x04, 0xa9, 0x77, 0x75,
	0x71, 0x56, 0xd2, 0x6e, 0x9d, 0x95, 0x0a, 0x8b, 0xb3, 0xd2, 0x5e, 0x1f, 0x60, 0xfe, 0x08, 0xb1,
	0x4e, 0x6e, 0x9e, 0x0d, 0x4e, 0x9e, 0x9f, 0xf6, 0xac, 0xc3, 0xde, 0xb3, 0xce, 0xf3, 0x13, 0xb3,
	0xf5, 0x1e, 0x63, 0xd5, 0x52, 0x98, 0x39, 0x38, 0x7d, 0x3a, 0x32, 0x07, 0xfd, 0x5e, 0x4b, 0x63,
	0x89, 0x47, 0x0a, 0x7d, 0xc9, 0x7c, 0x4f, 0x7a, 0x66, 0xcf, 0xea, 0x98, 0xad, 0xc2, 0x1e, 0x8e,
	0xc7, 0x3f, 0x99, 0xca, 0x3a, 0x54, 0x47, 0x66, 0x87, 0x6d, 0xe2, 0x17, 0x2c, 0x54, 0x1b, 0xb6,
	0xa4, 0xd5, 0x1d, 0x9c, 0x0e, 0x3b, 0x5d, 0xf3, 0x78, 0xd0, 0xb7, 0x46, 0xb8, 0xcb, 0xc2, 0xed,
	0xc2, 0x07, 0xb9, 0x1d, 0xb3, 0x83, 0x8f, 0x7a, 0x2c, 0xe6, 0x79, 0x59, 0x4c, 0xe3, 0xdf, 0xfe,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x45, 0x72, 0xde, 0x9b, 0x0b, 0x00, 0x00,
}
