.\"
.\" Author: Joao Marcelo Martins <marcelo.martins@rackspace.com> or <btorch@gmail.com>
.\" Copyright (c) 2010-2011 OpenStack, LLC.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"    http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
.\" implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"  
.TH swift-account-server 1 "8/26/2011" "Linux" "OpenStack Swift"

.SH NAME 
.LP
.B swift-account-server
\- Openstack-swift account server

.SH SYNOPSIS
.LP
.B swift-account-server
[CONFIG] [-h|--help] [-v|--verbose]

.SH DESCRIPTION 
.PP
The Account Server's primary job is to handle listings of containers. The listings
are stored as sqlite database files, and replicated across the cluster similar to how
objects are. 

.SH DOCUMENTATION
.LP
More in depth documentation in regards to 
.BI swift-account-server
and also about Openstack-Swift as a whole can be found at 
.BI http://swift.openstack.org/index.html
and 
.BI http://docs.openstack.org

.SH FILES
.IP "\fI/usr/share/doc/swift-account/account-server.conf-sample\fR" 0
Sample configuration file for swift-account server
.IP "\fI/etc/init.d/swift-account\fR" 0
Account server init.d script	
 


.SH "SEE ALSO"
.BR account-server.conf(5)
