.\"
.\" Author: Madhuri Kumari<madhuri.rai07@gmail.com>
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"    http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
.\" implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.TH swift-account-info 1 "10/25/2016" "Linux" "OpenStack Swift"

.SH NAME
.LP
.B swift-account-info
\- OpenStack Swift account-info tool

.SH SYNOPSIS
.LP
.B swift-account-info
<account_db_file> [options]

.SH DESCRIPTION
.PP
This is a very simple swift tool that allows a swiftop engineer to retrieve
information about an account that is located on the storage node. One calls
the tool with a given db file as it is stored on the storage node system.
It will then return several information about that account such as;

.PD 0
.IP  "- Account"
.IP  "- Account hash "
.IP  "- Created timestamp "
.IP  "- Put timestamp "
.IP  "- Delete timestamp "
.IP  "- Container Count "
.IP  "- Object count "
.IP  "- Bytes used "
.IP  "- Chexor "
.IP  "- ID"
.IP  "- User Metadata "
.IP  "- Ring Location"
.PD

.SH OPTIONS
.TP
\fB\-h, --help \fR
Shows the help message and exit
.TP
\fB\-d SWIFT_DIR, --swift-dir=SWIFT_DIR\fR
Pass location of swift configuration file if different from the default
location /etc/swift

.SH DOCUMENTATION
.LP
More documentation about OpenStack Swift can be found at
.BI https://docs.openstack.org/swift/latest/

.SH "SEE ALSO"

.BR swift-container-info(1),
.BR swift-get-nodes(1),
.BR swift-object-info(1)
