.\"
.\" Copyright (c) 2017 OpenStack Foundation.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"    http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
.\" implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.TH SWIFT-OBJECT-RELINKER "1" "December 2017" "OpenStack Swift"

.SH NAME
\fBswift\-object\-relinker\fR \- relink and cleanup objects to increase partition power
.SH SYNOPSIS
.B swift\-object\-relinker
[\fIoptions\fR] <\fIcommand\fR>

.SH DESCRIPTION
.PP
The relinker prepares an object server's filesystem for a partition power
change by crawling the filesystem and linking existing objects to future
partition directories.

More information can be found at
.BI https://docs.openstack.org/swift/latest/ring_partpower.html

.SH COMMANDS
.TP
\fBrelink\fR
Relink files for partition power increase.

.TP
\fBcleanup\fR
Remove hard links in the old locations.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit

.TP
\fB\-\-swift-dir\fR \fISWIFT_DIR\fR
Path to swift directory

.TP
\fB\-\-devices\fR \fIDEVICES\fR
Path to swift device directory

.TP
\fB\-\-skip\-mount\-check\fR
Don't test if disk is mounted

.TP
\fB\-\-logfile\fR \fILOGFILE\fR
Set log file name

.TP
\fB\-\-debug\fR
Enable debug mode

.SH DOCUMENTATION
.LP
More in depth documentation in regards to
.BI swift\-object\-relinker
and also about OpenStack Swift as a whole can be found at
.BI http://docs.openstack.org/developer/swift/index.html
and
.BI http://docs.openstack.org
