.\"
.\" Author: Joao Marcelo Martins <marcelo.martins@rackspace.com> or <btorch@gmail.com>
.\" Copyright (c) 2010-2011 OpenStack Foundation.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"    http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
.\" implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.TH swift-get-nodes 1 "10/25/2016" "Linux" "OpenStack Swift"

.SH NAME
.LP
.B swift-get-nodes
\- OpenStack Swift get-nodes tool

.SH SYNOPSIS
.LP
.B swift-get-nodes
\ [options] <ring.gz> <account> [<container> [<object>]]

Or

.B swift-get-nodes
[options] <ring.gz> -p <partition>

Or

.B swift-get-nodes
\ [options] -P policy_name <account> <container> <object>

.SH DESCRIPTION
.PP
The swift-get-nodes tool can be used to find out the location where
a particular account, container or object item is located within the
swift cluster nodes. For example, if you have the account hash and a container
name that belongs to that account, you can use swift-get-nodes to lookup
where the container resides by using the container ring.

.SH OPTIONS
.TP
\fB\-h --help \fR
Shows the help message and exit
.TP
\fB\-a, --all\fR
Show all handoff nodes
.TP
\fB\-p PARTITION, --partition=PARTITION\fR
Show nodes for a given partition
.TP
\fB\-P POLICY_NAME, --policy-name=POLICY_NAME \fR
Specify storage policy name
.TP
\fB\-d SWIFT_DIR, --swift-dir=SWIFT_DIR\fR
Pass location of swift configuration file if different from the default
location /etc/swift

.RS 0
.IP "\fIExample:\fR"
.RE

.RS 4
.PD 0
.IP "$ swift-get-nodes /etc/swift/account.ring.gz MyAccount-12ac01446be2"

.PD 0
.IP "Account     MyAccount-12ac01446be2"
.IP "Container   None"
.IP "Object      None"

.IP "Partition 221082"
.IP "Hash d7e6ba68cfdce0f0e4ca7890e46cacce"

.IP "Server:Port Device      172.24.24.29:6202 sdd"
.IP "Server:Port Device      172.24.24.27:6202 sdr"
.IP "Server:Port Device      172.24.24.32:6202 sde"
.IP "Server:Port Device      172.24.24.26:6202 sdv    [Handoff]"


.IP "curl -I -XHEAD http://172.24.24.29:6202/sdd/221082/MyAccount-12ac01446be2"
.IP "curl -I -XHEAD http://172.24.24.27:6202/sdr/221082/MyAccount-12ac01446be2"
.IP "curl -I -XHEAD http://172.24.24.32:6202/sde/221082/MyAccount-12ac01446be2"
.IP "curl -I -XHEAD http://172.24.24.26:6202/sdv/221082/MyAccount-12ac01446be2 # [Handoff]"

.IP "ssh 172.24.24.29 ls -lah /srv/node/sdd/accounts/221082/cce/d7e6ba68cfdce0f0e4ca7890e46cacce/ "
.IP "ssh 172.24.24.27 ls -lah /srv/node/sdr/accounts/221082/cce/d7e6ba68cfdce0f0e4ca7890e46cacce/"
.IP "ssh 172.24.24.32 ls -lah /srv/node/sde/accounts/221082/cce/d7e6ba68cfdce0f0e4ca7890e46cacce/"
.IP "ssh 172.24.24.26 ls -lah /srv/node/sdv/accounts/221082/cce/d7e6ba68cfdce0f0e4ca7890e46cacce/ # [Handoff] "

.PD
.RE

.SH DOCUMENTATION
.LP
More documentation about OpenStack Swift can be found at
.BI https://docs.openstack.org/swift/latest/



.SH "SEE ALSO"

.BR swift-account-info(1),
.BR swift-container-info(1),
.BR swift-object-info(1),
.BR swift-ring-builder(1)
