.\"
.\" Copyright (c) 2016 OpenStack Foundation.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"    http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
.\" implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.TH SWIFT-RECON-CRON "1" "August 2016" "OpenStack Swift"

.SH NAME
swift\-recon\-cron \- OpenStack Swift recon cron job

.SH SYNOPSIS
.B swift\-recon\-cron
\fI<CONFIG>\fR

.SH DESCRIPTION
.PP
Tool that can be run by using cron to fill recon cache. Recon data
can be read by \fBswift-recon\fR tool.

.SH DOCUMENTATION
.LP
More in depth documentation in regards to
.BI swift\-recon\-cron
and also about OpenStack Swift as a whole can be found at
.BI https://docs.openstack.org/swift/latest/
and
.BI https://docs.openstack.org
